set_property SRC_FILE_INFO {cfile:{C:/Users/aleja/Desktop/Uni/3Ao/6 Cuatrimestre/PHR/SistemaDeteccionGasesHogar/ECG_in_FPGA_Thesis/ECG_in_FPGA_Thesis.srcs/constrs_1/new/constraints.xdc} rfile:../../../ECG_in_FPGA_Thesis.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F21 [get_ports sw1]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports led0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports led1]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports clk]
